### PR TITLE
Update Dockerfile to base FROM Centos node4 image

### PR DESCRIPTION
**Pull request by philipgough**
Since Open sourcing this project we no longer want to inherit from RHEL image where user would need subscription in place to pull the Docker image.

### CODE REVIEW

**Comment by philipgough** [comment]
@maleck13 Can you review this when you get a chance please?

FYI @psturc @grdryn

**Comment by philipgough** [comment]
Relates to change to Jenkins job https://github.com/fheng/jenkins-bob-builder/pull/175

**Review by grdryn — APPROVED** [review]
👍

**Comment by PhilipGough** [comment]
Retest this please

**Comment by PhilipGough** [comment]
Retest this please

**Comment by philipgough** [comment]
Retest this please

**Pull request merged**
