### PR TITLE
added dev dockerfile, conf file & updated readme

### PR DESCRIPTION
**Pull request by cfoskin**

### CODE REVIEW

**Comment by cfoskin** [comment]
retest this please

**Comment by cfoskin** [comment]
retest this please

**Review by maleck13 — COMMENTED** [review]
Changes look fine. Just unsure about why we need a new config file

**Comment by cfoskin** [comment]
@maleck13 Updated now to add extra step to readme instead & removed extra config file.

**Review by maleck13 — APPROVED** [review]
this looks fine to me

**Pull request merged**
